#!/bin/sh

# Language
export LANG="ja_JP.UTF-8"

# Font
xset fp+ /usr/pkg/share/fonts/X11/TTF/

# No bell
xset b off

# Keyboard layout
setxkbmap -model us -layout us -option ctrl:nocaps

# For inputmethod/ibus-mozc
export XMODIFIERS="@im=ibus"
export GTK_IM_MODULE="ibus"
export QT_IM_MODULE="ibus"
export DefaultIMModule="ibus"

# For i3-dmenu-desktop
export XDG_DATA_DIRS="/usr/pkg/share:$XDG_DATA_DIRS"

/usr/pkg/bin/ibus-daemon -drx
/usr/pkg/bin/i3
