#!/bin/sh

##
# Third party prefix (mainly, pkgsrc or ports)
prefix="/usr/pkg"

##
# Language
export LANG="ja_JP.UTF-8"

##
# Font
xset fp+ $prefix/share/fonts/X11/TTF/
# xset fp+ /usr/local/share/fonts/TTF/

##
# No bell
xset b off

##
# Keyboard layout
setxkbmap -model us -layout us -option ctrl:nocaps

##
# Input method
if command -v ibus-daemon > /dev/null && command -v mozc > /dev/null; then
    # ibus-mozc
    export XMODIFIERS="@im=ibus"
    export GTK_IM_MODULE="ibus"
    export QT_IM_MODULE="ibus"
    export DefaultIMModule="ibus"
    $prefix/bin/ibus-daemon -drx
elif command -v fcitx > /dev/null && command -v mozc > /dev/null; then
    # fcitx-mozc
    export GTK_IM_MODULE="fcitx"
    export QT_IM_MODULE="xim"
    export XMODIFIERS="@im=fcitx"
    $prefix/bin/mozc start
    $prefix/bin/fcitx -r -d
fi

##
# For i3-dmenu-desktop
export XDG_DATA_DIRS="$prefix/share:$XDG_DATA_DIRS"

##
# Window Manager
$prefix/bin/i3
