# $NetBSD$
DISTNAME=	uki-desktop-20191013
CATEGORIES=	meta-pkgs
MASTER_SITES=	# empty

MAINTAINER=	uki@NetBSD.org
HOMEPAGE=	https://e-yuuki.org
COMMENT=	Meta package for my develop environment

DEPENDS+=	weechat-[0-9]*:../../chat/weechat
DEPENDS+=	exctags-[0-9]*:../../devel/exctags
DEPENDS+=	git-[0-9]*:../../devel/git
DEPENDS+=	global-[0-9]*:../../devel/global
DEPENDS+=	go-tools-[0-9]*:../../devel/go-tools
DEPENDS+=	mercurial-[0-9]*:../../devel/mercurial
DEPENDS+=	vim-[0-9]*:../../editors/vim
DEPENDS+=	noto-ttf-[0-9]*:../../fonts/noto-ttf
DEPENDS+=	ricty-ttf-[0-9]*:../../fonts/ricty-ttf
DEPENDS+=	feh-[0-9]*:../../graphics/feh
DEPENDS+=	ibus-mozc-[0-9]*:../../inputmethod/ibus-mozc
# DEPENDS+=	npm-[0-9]*:../../lang/npm
DEPENDS+=	go-[0-9]*:../../lang/go
DEPENDS+=	python37-[0-9]*:../../lang/python37
DEPENDS+=	tmux-[0-9]*:../../misc/tmux
DEPENDS+=	neomutt-[0-9]*:../../mail/neomutt
DEPENDS+=	pkg_comp-[0-9]*:../../pkgtools/pkg_comp
DEPENDS+=	pkg_install-[0-9]*:../../pkgtools/pkg_install
DEPENDS+=	pkgin-[0-9]*:../../pkgtools/pkgin
DEPENDS+=	cy2-plain-[0-9]*:../../security/cy2-plain # Auth for Gmail
DEPENDS+=	gnupg2-[0-9]*:../../security/gnupg2
DEPENDS+=	openssh-[0-9]*:../../security/openssh
DEPENDS+=	password-store-[0-9]*:../../security/password-store
DEPENDS+=	zsh-[0-9]*:../../shells/zsh
DEPENDS+=	zsh-autosuggestions-[0-9]*:../../shells/zsh-autosuggestions
DEPENDS+=	zsh-completions-[0-9]*:../../shells/zsh-completions
DEPENDS+=	zsh-syntax-highlighting-[0-9]*:../../shells/zsh-syntax-highlighting
DEPENDS+=	pcmanfm-[0-9]*:../../sysutils/pcmanfm
DEPENDS+=	i3status-[0-9]*:../../sysutils/i3status
DEPENDS+=	qemu-nvmm-[0-9]*:../../wip/qemu-nvmm
DEPENDS+=	i3-[0-9]*:../../wm/i3
DEPENDS+=	firefox-[0-9]*:../../www/firefox
DEPENDS+=	w3m-[0-9]*:../../www/w3m
DEPENDS+=	arandr-[0-9]*:../../x11/arandr
DEPENDS+=	dmenu-[0-9]*:../../x11/dmenu
DEPENDS+=	rxvt-unicode-[0-9]*:../../x11/rxvt-unicode
DEPENDS+=	xclip-[0-9]*:../../x11/xclip

META_PACKAGE=	yes

.include "../../mk/bsd.pkg.mk"
