DISTNAME=	uki-desktop-1.0
CATEGORIES=	meta-pkgs
MASTER_SITES=	# empty

MAINTAINER=	uki@NetBSD.org
COMMENT=	Meta package for my develop environment

DEPENDS+=	weechat-[0-9]*:../../chat/weechat
DEPENDS+=	git-[0-9]*:../../devel/git
DEPENDS+=	exctags-[0-9]*:../../devel/exctags
DEPENDS+=	vim-[0-9]*:../../editors/vim
DEPENDS+=	noto-emoji-ttf-[0-9]*:../../fonts/noto-emoji-ttf
DEPENDS+=	ricty-ttf-[0-9]*:../../fonts/ricty-ttf
DEPENDS+=	feh-[0-9]*:../../graphics/feh
DEPENDS+=	ibus-mozc-[0-9]*:../../inputmethod/ibus-mozc
DEPENDS+=	npm-[0-9]*:../../lang/npm
DEPENDS+=	neomutt-[0-9]*:../../mail/neomutt
DEPENDS+=	pkgin-[0-9]*:../../pkgtools/pkgin
DEPENDS+=	pkg_comp-[0-9]*:../../pkgtools/pkg_comp
DEPENDS+=	cy2-plain-[0-9]*:../../security/cy2-plain # Auth for Gmail
DEPENDS+=	gnupg2-[0-9]*:../../security/gnupg2
DEPENDS+=	password-store-[0-9]*:../../security/password-store
DEPENDS+=	zsh-[0-9]*:../../shells/zsh
DEPENDS+=	zsh-autosuggestions-[0-9]*:../../shells/zsh-autosuggestions
DEPENDS+=	zsh-completions-[0-9]*:../../shells/zsh-completions
DEPENDS+=	zsh-syntax-highlighting-[0-9]*:../../shells/zsh-syntax-highlighting
DEPENDS+=	pcmanfm-[0-9]*:../../sysutils/pcmanfm
DEPENDS+=	i3status-[0-9]*:../../sysutils/i3status
DEPENDS+=	i3-[0-9]*:../../wm/i3
DEPENDS+=	firefox-[0-9]*:../../www/firefox
DEPENDS+=	w3m-[0-9]*:../../www/w3m
DEPENDS+=	arandr-[0-9]*:../../x11/arandr
DEPENDS+=	rxvt-unicode-[0-9]*:../../x11/rxvt-unicode
DEPENDS+=	xclip-[0-9]*:../../x11/xclip

META_PACKAGE=	yes

.include "../../mk/bsd.pkg.mk"
