#!/bin/sh

disk="example.qcow2"
helper="/usr/libexec/qemu-bridge-helper"

qemu_cmd="/usr/libexec/qemu-kvm"

case $1 in
create)
    ;;
destroy)
    ;;
start)
    ;;
install)
    ;;
esac

$qemu_cmd \
    -hda            "$disk" \
    -smp            2 \
    -m              2048 \
    -net            nic,model=virtio \
    -net            bridge,br=br0,helper="$helper" \
    -vnc            :0 \
    --enable-kvm \
    -daemonize
